### PR TITLE
feat: add sessions to zipline

### LINKED ISSUE #552: Bug: Session doesn't invalidate when password is changed
### What happened?

When you change your Zipline account password, existing sessions do not get invalidated, and they stay signed in. This can be a security risk if your account got hacked.

### Version

latest (ghcr.io/diced/zipline or ghcr.io/diced/zipline:latest)

### What browser(s) are you seeing the problem on?

Firefox, Chromium-based (Chrome, Edge, Brave, Opera, mobile chrome/chromium based, etc)

### Zipline Logs

_No response_

### Browser Logs

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by TacticalTechJay**
This should resolve #552.

This PR adds sessions, here's how it'll work
 - a session's default lifetime will follow the cookie's expiration date of 2 weeks
 - a daily interval for clearing out dead sessions
 - changing the password to a user will invalidate current sessions for said user
 - listing a user's own sessions in their manage user page

Oh and I may have changed the devcontainer a little :3

~~made this in a day xd~~

### CODE REVIEW

**Comment by diced** [comment]
getting this in logs when changing password and accessing another link on zipline while in a incognito window
```
2024-05-22 09:06:57,720 PM debug [withZipline] Cannot read properties of null (reading 'sessions')
```
Screenshot_20240522_210849

**Comment by TacticalTechJay** [comment]
Drafted cuz I'll be spending a _looot_ of time figuring it out.

**Comment by TacticalTechJay** [comment]
Screw it, we ballin'. Give this one a try

**Comment by diced** [comment]
Seems like it works but when a session is invalidated, you can still navigate through the dashboard but all the API calls fail with "not logged in"

**Comment by diced** [comment]
Closing this since it's being implemented in v4 but differently.

**Pull request closed without merging**
