### PR TITLE
Allow Redirect URI Configuration

### PR DESCRIPTION
**Pull request by Digital39999**
This helps a lot when you have tunneling setup.

### CODE REVIEW

**Review by TacticalTechJay — CHANGES_REQUESTED** [review]
It looks like there's no option to enable or disable the discord user whitelist... Make another config variable to enable or disable it.

**Comment by diced** [comment]
> It looks like there's no option to enable or disable the discord user whitelist... Make another config variable to enable or disable it.

It should default to an empty array - which means its disabled. Good PR anyway!

**Comment by Digital39999** [comment]
Wait actually, empty array doesn't mean it's disabled, will correct this.

**Review by Digital39999 — COMMENTED** [review]
Everything should be ready now.

**Review by TacticalTechJay — APPROVED** [review]
Alright, this looks good to me!

**Comment by TacticalTechJay** [comment]
But it seems like the commits still have to be signed.

**Comment by Digital39999** [comment]
Isn't it kinda late for that or?

**Comment by TacticalTechJay** [comment]
Yeah, it sort of is. Maybe @diced can force merge?

**Comment by Digital39999** [comment]
Well i tried to sign them, but doesn't seem to be possible on already committed ones.

**Comment by diced** [comment]
It's fine, but remember to sign your commits if you pr again :)

I will be updating the documentation when this is merged, so don't worry about making a pr for that on the docs repo

**Review by diced — APPROVED** [review]

**Pull request merged**
