### PR TITLE
Feat(?): Add some sort of queueing for the thumbnail worker.

### PR DESCRIPTION
**Pull request by TacticalTechJay**
A

### CODE REVIEW

**Comment by TacticalTechJay** [comment]
This is my idea of hopefully fixing #425. I do *not* have the amount of videos the author of the issue has but, I sincerely hope it's enough.

**Comment by TacticalTechJay** [comment]
This is a **draft** and shouldn't be used in production as this hasn't been tested to its fullest extent

**Comment by diced** [comment]
I'm not sure if this works correctly, some of the thumbnails are being cut short, like not the full height of the video thumbnail. My guess is that its going too fast and the ffmpeg commands have not finished running? This also might be an underlying issue with the thumbnail generator though.

Another thing: suggest using a more descriptive name for the worker-queue instead of `$`, and the loggers in the workers should be something else as they handle multiple videos now, maybe a unique identifier with randomChars.

**Comment by diced** [comment]
Closing as a fix for this was pushed to trunk.

**Pull request closed without merging**
