### PR TITLE
db(prisma); seed after applying migrations

### PR DESCRIPTION
**Pull request by AlphaNecron**

### CODE REVIEW

**Comment by diced** [comment]
Will not be adding this as Zipline's seed file will be removed in an upcoming update as it was never used for a long time. It has been replaced by when the user logs in for the first time, it will create a user account.

**Comment by AlphaNecron** [comment]
Oh, then generate after migrating only?

**Comment by diced** [comment]
Well, even if this were merged it would just create a new administrator account ever time a db change is made (causing a migration to run), either way the seed has not been used in forever and will probably get removed in a upcoming release.

**Comment by AlphaNecron** [comment]
Oh.

**Pull request closed without merging**
