### PR TITLE
Add Catppuccin themes

### PR DESCRIPTION
**Pull request by cswimr**
This PR adds [Catppuccin](https://catppuccin.com) themes to v3. v4 PR will come later as well, don't have the time for it at the moment.

image
image
image
image

### CODE REVIEW

**Comment by diced** [comment]
This might just be my personal preference, but the appshell background color on catppuccin_latte seems a bit too dark, and isn't really fitting into the light theme. I think it would be better if it was a bit lighter. The other themes look great, and feel free to take your time bringing them over to v4.

Also the palette link on all of them are misspelled, instead of https://catppuccin.com/pallete it should be https://catppuccin.com/palette

**Comment by cswimr** [comment]
Alright, I can look at it later. All of the colors I'm using are from https://catppuccin.com/palette (with the exception of the accenting colors, which are variations of each theme's Blue accent), so if there's another color from Latte that you think would look better as the appshell background, I can swap it around.

**Comment by diced** [comment]
:skull: didn't mean to do that whoops

**Comment by diced** [comment]
well what I meant to do was in this commit https://github.com/diced/zipline/commit/5e37d89b18e6f32edfebd558178b7d5271c25fb5

for some reason mantine doesn't let you even change the light colors for light themes, so the workaround here is just setting the color scheme to dark, but using the light colors. it works so whatever :)

**Comment by NeonGamerBot-QK** [comment]
catppuccin :D

**Comment by NeonGamerBot-QK** [comment]
@cswimr you should prob create an issue  at the catpuccin repo if you added this to zipline

**Pull request merged**
