### PR TITLE
Change outdated url.

### PR DESCRIPTION
**Pull request by ar06x**
Change the url in the Manage User page to the new updated URL ([https://zipline.diced.tech/docs/guides/variables](https://zipline.diced.tech/docs/guides/variables))

### CODE REVIEW

**Comment by diced** [comment]
@Wolfy0615 Please resolve the merge conflicts.

**Review by diced — CHANGES_REQUESTED** [review]
The link should be https://zipline.diced.tech/docs/guides/variables instead of https://zipline.diced.tech/docs/variables

**Comment by ar06x** [comment]
> https://zipline.diced.tech/docs/guides/variables

Whoops, my bad

**Review by diced — APPROVED** [review]
LGTM, will merge after actions finish.

**Pull request merged**
